name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install flake8
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8

      - name: Run linting tests
        run: |
          python3 -m flake8 --count --statistics --show-source
